# Generated by Claude Opus 4.6

#!/bin/bash

# =============================================================
# 🖥️ Fedora Post-Install: RPM Fusion & Multimedia Setup Script
# =============================================================

set -euo pipefail

# --- Colors ---
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

info()  { echo -e "${GREEN}[✔]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[✘]${NC} $1"; exit 1; }

# --- Must run as root ---
if [[ $EUID -ne 0 ]]; then
    error "Please run this script with sudo or as root."
fi

FEDORA_VERSION=$(rpm -E %fedora)
info "Detected Fedora version: $FEDORA_VERSION"

# =========================
# 1. Enable RPM Fusion Repos
# =========================
if rpm -q rpmfusion-free-release &>/dev/null && rpm -q rpmfusion-nonfree-release &>/dev/null; then
    warn "RPM Fusion repos already installed — skipping."
else
    info "Installing RPM Fusion Free and Non-Free repositories..."
    dnf install -y \
        "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-${FEDORA_VERSION}.noarch.rpm" \
        "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-${FEDORA_VERSION}.noarch.rpm"
fi

info "Installing AppStream metadata..."
dnf install -y rpmfusion-*-appstream-data

# =========================
# 2. Multimedia Codecs
# =========================
if rpm -q ffmpeg &>/dev/null; then
    warn "Full FFmpeg already installed — skipping swap."
else
    info "Switching to full FFmpeg..."
    dnf swap -y ffmpeg-free ffmpeg --allowerasing
fi

info "Installing additional multimedia codecs..."
dnf update -y @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin

# =========================
# 3. Hardware-Accelerated Video
# =========================
echo ""
echo "========================================="
echo "  Select your GPU for VA-API drivers:"
echo "========================================="
echo "  1) Intel"
echo "  2) AMD"
echo "  3) NVIDIA"
echo "  4) Skip"
echo "========================================="
read -rp "Enter choice [1-4]: " gpu_choice

case $gpu_choice in
    1)
        info "Installing Intel VA-API driver..."
        dnf install -y intel-media-driver
        ;;
    2)
        info "Installing AMD VA-API drivers..."
        dnf swap -y mesa-va-drivers mesa-va-drivers-freeworld
        dnf install -y mesa-va-drivers-freeworld.i686
        ;;
    3)
        info "Installing NVIDIA VA-API drivers..."
        dnf install -y libva-nvidia-driver.{i686,x86_64}
        ;;
    4)
        warn "Skipping GPU driver installation."
        ;;
    *)
        warn "Invalid choice — skipping GPU driver installation."
        ;;
esac

# =========================
# 4. Additional Firmware
# =========================
info "Enabling tainted non-free repo..."
dnf install -y rpmfusion-nonfree-release-tainted

info "Installing additional firmware..."
dnf --repo=rpmfusion-nonfree-tainted install -y "*-firmware"

# =========================
# Done
# =========================
echo ""
info "🎉 All done! A reboot is recommended."
read -rp "Reboot now? [y/N]: " reboot_choice
if [[ "$reboot_choice" =~ ^[Yy]$ ]]; then
    systemctl reboot
fi
